repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: '^demos/'
        args: [--markdown-linebreak-ext=md]
      - id: requirements-txt-fixer
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: '^demos/'
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        exclude: '^demos/'
        additional_dependencies: [ Flake8-pyproject ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy
        exclude: '^demos/'
        additional_dependencies: [
            types-requests==2.28.11.7,
            types-setuptools==65.6.0.3,
            types-tqdm==4.64.7.9,
            types-urllib3==1.26.25.4,
            types-PyYAML==6.0.12.12]
