analyzers: []
model_first: "ft:gpt-3.5-turbo-1106:personal::8LCi9Q0d"
model_feedback: "gpt-3.5-turbo"
feedback_variant: "separate"
system_prompt: 2023-11-15_GPT-Builder.txt
dataset: "eval"
max_iter: 5
log_conversation: true
scores: [
  "extrinsic.levenshtein_distance_score",
  "extrinsic.bleu_score",
  "extrinsic.trf_similarity_score",
  "extrinsic.sequence_matcher_score",
]
